.TH PSPVC 1 "July 2026" "pspvc 0.4" "User Commands"
.SH NAME
pspvc \- PSP video converter GUI
.SH SYNOPSIS
.B pspvc
.SH DESCRIPTION
pspvc is a GTK3 graphical frontend for converting video files for playback
on the Sony PlayStation Portable (PSP). It uses ffmpeg for actual encoding.
.SH AUTHOR
RingtailedFox
.SH LICENSE
GPL-2+. See /usr/share/common-licenses/GPL-2.
