## Process this file with automake to produce Makefile.in

## Created by Anjuta - will be overwritten
## If you don't want it to overwrite it,
## 	Please disable it in the Anjuta project configuration

pspvc_pixmapsdir = $(prefix)/@NO_PREFIX_PACKAGE_PIXMAPS_DIR@

pspvc_pixmaps_DATA = \
	pspvc_09.png\
	pspvc_logo.png\
	pspvc_thm.png\
	psp-console.png

EXTRA_DIST = $(pspvc_pixmaps_DATA)
